# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import invoice_pb2 as invoice__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in invoice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InvoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateInvoice = channel.unary_unary(
                '/invoice.InvoiceService/CreateInvoice',
                request_serializer=invoice__pb2.CreateInvoiceRequest.SerializeToString,
                response_deserializer=invoice__pb2.InvoiceResponse.FromString,
                _registered_method=True)
        self.GetInvoice = channel.unary_unary(
                '/invoice.InvoiceService/GetInvoice',
                request_serializer=invoice__pb2.GetInvoiceRequest.SerializeToString,
                response_deserializer=invoice__pb2.InvoiceResponse.FromString,
                _registered_method=True)
        self.ListInvoices = channel.unary_unary(
                '/invoice.InvoiceService/ListInvoices',
                request_serializer=invoice__pb2.ListInvoicesRequest.SerializeToString,
                response_deserializer=invoice__pb2.ListInvoicesResponse.FromString,
                _registered_method=True)
        self.UpdateInvoice = channel.unary_unary(
                '/invoice.InvoiceService/UpdateInvoice',
                request_serializer=invoice__pb2.UpdateInvoiceRequest.SerializeToString,
                response_deserializer=invoice__pb2.InvoiceResponse.FromString,
                _registered_method=True)
        self.DeleteInvoice = channel.unary_unary(
                '/invoice.InvoiceService/DeleteInvoice',
                request_serializer=invoice__pb2.DeleteInvoiceRequest.SerializeToString,
                response_deserializer=invoice__pb2.DeleteInvoiceResponse.FromString,
                _registered_method=True)
        self.InitiatePayment = channel.unary_unary(
                '/invoice.InvoiceService/InitiatePayment',
                request_serializer=invoice__pb2.PaymentRequest.SerializeToString,
                response_deserializer=invoice__pb2.PaymentResponse.FromString,
                _registered_method=True)


class InvoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInvoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvoice,
                    request_deserializer=invoice__pb2.CreateInvoiceRequest.FromString,
                    response_serializer=invoice__pb2.InvoiceResponse.SerializeToString,
            ),
            'GetInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoice,
                    request_deserializer=invoice__pb2.GetInvoiceRequest.FromString,
                    response_serializer=invoice__pb2.InvoiceResponse.SerializeToString,
            ),
            'ListInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInvoices,
                    request_deserializer=invoice__pb2.ListInvoicesRequest.FromString,
                    response_serializer=invoice__pb2.ListInvoicesResponse.SerializeToString,
            ),
            'UpdateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInvoice,
                    request_deserializer=invoice__pb2.UpdateInvoiceRequest.FromString,
                    response_serializer=invoice__pb2.InvoiceResponse.SerializeToString,
            ),
            'DeleteInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInvoice,
                    request_deserializer=invoice__pb2.DeleteInvoiceRequest.FromString,
                    response_serializer=invoice__pb2.DeleteInvoiceResponse.SerializeToString,
            ),
            'InitiatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiatePayment,
                    request_deserializer=invoice__pb2.PaymentRequest.FromString,
                    response_serializer=invoice__pb2.PaymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'invoice.InvoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('invoice.InvoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InvoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoice.InvoiceService/CreateInvoice',
            invoice__pb2.CreateInvoiceRequest.SerializeToString,
            invoice__pb2.InvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoice.InvoiceService/GetInvoice',
            invoice__pb2.GetInvoiceRequest.SerializeToString,
            invoice__pb2.InvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoice.InvoiceService/ListInvoices',
            invoice__pb2.ListInvoicesRequest.SerializeToString,
            invoice__pb2.ListInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoice.InvoiceService/UpdateInvoice',
            invoice__pb2.UpdateInvoiceRequest.SerializeToString,
            invoice__pb2.InvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoice.InvoiceService/DeleteInvoice',
            invoice__pb2.DeleteInvoiceRequest.SerializeToString,
            invoice__pb2.DeleteInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoice.InvoiceService/InitiatePayment',
            invoice__pb2.PaymentRequest.SerializeToString,
            invoice__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
