# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoice.proto\">\n\x0eInvoiceRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08supplier\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"!\n\x0fInvoiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2D\n\x0eInvoiceService\x12\x32\n\rCreateInvoice\x12\x0f.InvoiceRequest\x1a\x10.InvoiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOICEREQUEST']._serialized_start=17
  _globals['_INVOICEREQUEST']._serialized_end=79
  _globals['_INVOICERESPONSE']._serialized_start=81
  _globals['_INVOICERESPONSE']._serialized_end=114
  _globals['_INVOICESERVICE']._serialized_start=116
  _globals['_INVOICESERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
